DIRS=eval models parsed
MALT?=malt

# TODO
.PHONY: all clean

# This makes make keep intermediate files generated by wildcard rules when
# make exits. We actually want to keep intermediate files (like parser models)
# even if we instruct make to create the parsed file.
.SECONDARY:

all:

# The numbers in these two rules split the corpus into 90% training and 10%
# test.
corpora/norwegian.conll: corpora/norwegian-full.conll
	head -n 97470 $< > $@

corpora/norwegian-test.conll: corpora/norwegian-full.conll
	tail -n +97471 $< > $@

# Training and parsing:
models/%.mco: corpora/%.conll | models
	cd models && $(MALT) -m learn -c $* -l liblinear -a nivreeager -i ../$<

parsed/%-danish.conll: corpora/%.conll models/danish.mco | parsed
	./scripts/single-root.pl <(cd models && $(MALT) -m parse -c danish -i ../$<) | awk -f scripts/no-nobj.awk > $@

parsed/%-norwegian.conll: corpora/%.conll models/norwegian.mco | parsed
	./scripts/single-root.pl <(cd models && $(MALT) -m parse -c norwegian -i ../$<) | awk -f scripts/no-nobj.awk > $@

parsed/%-swedish.conll: corpora/%.conll models/swedish.mco | parsed
	./scripts/single-root.pl <(cd models && $(MALT) -m parse -c swedish -i ../$<) | awk -f scripts/no-nobj.awk > $@

parsed/%-caterpillar.conll: scripts/make-caterpillar.awk corpora/%.conll | parsed
	awk -f $< corpora/$*.conll > $@

# Utility stuff:
$(DIRS):
	mkdir $@

clean:
	rm -rf $(DIRS)
